function nabla_x_f_z_z_d_eval = analytical_grad(Ts,z,d)
%ANALYTICAL_GRAD
%    NABLA_X_F_Z_Z_D_EVAL = ANALYTICAL_GRAD(Ts,z(1,1),z(2,1),z(3,1),z(4,1),z(5,1),d(1,1),d(2,1))

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Aug-2023 14:55:38

t2 = Ts.*z(5,1);
t3 = Ts.^2;
t4 = z(3,1).^2;
t5 = z(4,1).^2;
t8 = 1.0./z(5,1);
t6 = cos(t2);
t7 = sin(t2);
t9 = t8.^2;
t10 = t4+t5;
t11 = t6-1.0;
t12 = t10.^(3.0./2.0);
t14 = 1.0./sqrt(t10);
t13 = t8.*t11;
t15 = 1.0./t12;
t16 = t6.*t12;
t17 = t7.*t12.*2.0;
t18 = Ts.*d(1,1).*t15.*z(3,1).*z(4,1);
t20 = (d(1,1).*t3.*t15.*z(3,1).*z(4,1))./2.0;
t19 = -t18;
t21 = -t20;
nabla_x_f_z_z_d_eval = reshape([1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,(t8.*t15.*(t17+Ts.*d(1,1).*t2.*t5))./2.0,-t13+t21,t15.*(t16+Ts.*d(1,1).*t5),t7+t19,0.0,t13+t21,(t8.*t15.*(t17+Ts.*d(1,1).*t2.*t4))./2.0,-t7+t19,t15.*(t16+Ts.*d(1,1).*t4),0.0,-t7.*t9.*z(3,1)-t9.*t11.*z(4,1)+Ts.*t6.*t8.*z(3,1)-Ts.*t7.*t8.*z(4,1),-t7.*t9.*z(4,1)+t9.*t11.*z(3,1)+Ts.*t6.*t8.*z(4,1)+Ts.*t7.*t8.*z(3,1),-Ts.*t6.*z(4,1)-Ts.*t7.*z(3,1),Ts.*t6.*z(3,1)-Ts.*t7.*z(4,1),1.0,(t3.*t14.*z(3,1))./2.0,(t3.*t14.*z(4,1))./2.0,Ts.*t14.*z(3,1),Ts.*t14.*z(4,1),0.0,0.0,0.0,0.0,0.0,Ts],[5,7]);
