function F_eval = computeFJacobian(Ts,z_k)
%computeFJacobian
%    F_eval = computeFJacobian(Ts,z_k(1,1),z_k(2,1),z_k(3,1),z_k(4,1),z_k(5,1))

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Aug-2023 14:51:14

t2 = Ts.*z_k(5,1);
t5 = 1.0./z_k(5,1);
t3 = cos(t2);
t4 = sin(t2);
t6 = t5.^2;
t7 = t3-1.0;
t8 = t4.*t5;
t9 = t5.*t7;
F_eval = reshape([1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,t8,-t9,t3,t4,0.0,t9,t8,-t4,t3,0.0,-Ts.*t8.*z_k(4,1)-t4.*t6.*z_k(3,1)-t6.*t7.*z_k(4,1)+Ts.*t3.*t5.*z_k(3,1),Ts.*t8.*z_k(3,1)-t4.*t6.*z_k(4,1)+t6.*t7.*z_k(3,1)+Ts.*t3.*t5.*z_k(4,1),-Ts.*t3.*z_k(4,1)-Ts.*t4.*z_k(3,1),Ts.*t3.*z_k(3,1)-Ts.*t4.*z_k(4,1),1.0],[5,5]);
