function nabla_z_h_eval = constr_analytical_grad(z,psi_ego,X_ego,Y_ego)
%CONSTR_ANALYTICAL_GRAD
%    NABLA_Z_H_EVAL = CONSTR_ANALYTICAL_GRAD(z(1,1),z(2,1),PSI_EGO,X_ego,Y_ego)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Aug-2023 16:04:46

t2 = cos(psi_ego);
t3 = sin(psi_ego);
t4 = t2.*z(1,1);
t5 = t2.*z(2,1);
t6 = t3.*z(1,1);
t7 = t3.*z(2,1);
t8 = -t7;
t9 = Y_ego+t5+t6;
t10 = X_ego+t4+t8;
t11 = t9.^2;
t12 = t10.^2;
t13 = t11+t12;
t14 = 1.0./sqrt(t13);
nabla_z_h_eval = [t14.*(z(1,1)+X_ego.*t2+Y_ego.*t3),t14.*(z(2,1)-X_ego.*t3+Y_ego.*t2),0.0,0.0,0.0];
